name: Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "What is the image tag?"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t irezden/numberapi:${{ inputs.version }}
