name: Docker Image CI

on:

  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Enter Image tag:"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/numberapi:${{ inputs.version }}
    
    - uses: actions/checkout@v4
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/numberapi:${{ inputs.version }}
